
import React, { useState, useMemo, useEffect } from 'react';
import { 
  LayoutDashboard, 
  Users, 
  Settings, 
  Search, 
  Bell, 
  TrendingUp, 
  AlertTriangle, 
  CheckCircle2, 
  PieChart,
  Globe,
  Map as MapIcon,
  Save,
  Check,
  Activity,
  ArrowUpRight
} from 'lucide-react';

import StatsCard from './components/StatsCard';
import ParetoChart from './components/ParetoChart';
import ActivePartnersChart from './components/ActivePartnersChart';
import PartnerManager from './components/PartnerManager';
import MapDistribution from './components/MapDistribution';
import { Partner, Segment, ContractStatus } from './types';

// NOVA BASE DE DADOS REAL (Extraída do prompt)
const rawPartnerDatabase = [
  ["Ritma – Centro de Arritmias", Segment.HEALTH],
  ["AMI - ATENDIMENTO INTEGRADO", Segment.HEALTH],
  ["KAMILA PEREIRA FARIA PIO", Segment.HEALTH],
  ["COE ODONTOLOGIA", Segment.HEALTH],
  ["Labormed", Segment.HEALTH],
  ["CLINICA PULMO CARE , ENDOCRINO,PNEMO E CLINICO GERAL", Segment.HEALTH],
  ["Cardiologia Plena", Segment.HEALTH],
  ["CEPRO – Clínica Especializada em Periodontia e Reabilitação Oral", Segment.HEALTH],
  ["CET- Centro de Estudo e Terapia", Segment.HEALTH],
  ["Clínica Avivamente", Segment.HEALTH],
  ["Clínica Cristo Redentor", Segment.HEALTH],
  ["Clínica de Psicologia Infantil e Adulto", Segment.HEALTH],
  ["Clínica Mais Saúde Aqui", Segment.HEALTH],
  ["Clínica Plástica Dr. Daniel Thomaz", Segment.HEALTH],
  ["Clínica Rodrigo Pacheco", Segment.HEALTH],
  ["Consultório Dra. Nayara Silvestre", Segment.BEAUTY],
  ["Consultório Odontológico Dr. Rogério R. Vasconcelos", Segment.HEALTH],
  ["Consultório Pacaembu", Segment.HEALTH],
  ["Cuidar – Espelho do Futuro", Segment.HEALTH],
  ["Darlene Almeida Massoterapia", Segment.BEAUTY],
  ["Dr Warley Pereira de Paula", Segment.HEALTH],
  ["MINHA MÉDICA DA FAMÍLIA PRIME", Segment.HEALTH],
  ["GUSTAVO PAFUME DE SA", Segment.HEALTH],
  ["LETICIA ALVES DA SILVA", Segment.HEALTH],
  ["CEO OLHOS", Segment.HEALTH],
  ["Farma Uberlândia", Segment.HEALTH],
  ["Farmácia Artesani", Segment.HEALTH],
  ["Fisiolife", Segment.HEALTH],
  ["Fisioterapia para Idosos", Segment.HEALTH],
  ["Gaspa", Segment.HEALTH],
  ["Gastro Rondon", Segment.HEALTH],
  ["H OLHOS", Segment.HEALTH],
  ["IGEP – Instituto de Gastroenterologia Endoscopia e Proctologia", Segment.HEALTH],
  ["Industrial Pharma", Segment.HEALTH],
  ["Infisio-Reabilitação e Especialidades", Segment.HEALTH],
  ["AGRO SOUSA", Segment.PET],
  ["DRA ADRIANA EMI", Segment.HEALTH],
  ["PAULO MARCIO COELHO CARVAHO", Segment.HEALTH],
  ["CLÍNICA DE OLHOS SANTA CLARA", Segment.HEALTH],
  ["OPTICA E FOTOS BELA VISTA", Segment.OTHER],
  ["CLINICA DE OLHOS SILVESTRE CUSTODIO", Segment.HEALTH],
  ["DR.MARIÂNGELA TIBERY", Segment.HEALTH],
  ["REJANE DE OLIVEIRA BATISTA", Segment.HEALTH],
  ["GISELE RODRIGUES ALVES FIGUEIREDO", Segment.HEALTH],
  ["HUGO GOMES SANTOS (CENTRO DA VISÃO)", Segment.HEALTH],
  ["DR.FREDERICO TIBERY", Segment.HEALTH],
  ["EMAGRESEMPRE", Segment.BEAUTY],
  ["LIANE ABRAHÃO FRANGE CUNHA", Segment.HEALTH],
  ["ANDREIA NUNES CAMPOS", Segment.HEALTH],
  ["RADIOCLINICA", Segment.HEALTH],
  ["HUANG YU SHENG", Segment.HEALTH],
  ["PRO IMAGEM DIAGNOSTICO POR IMAGEM LTDA", Segment.HEALTH],
  ["CRISTIANE DIAS GONDIM", Segment.HEALTH],
  ["Uroped – Especialistas Médicos Associados", Segment.HEALTH],
  ["Visão Center", Segment.HEALTH],
  ["Vittalev Farmácia de Manipulação", Segment.HEALTH],
  ["AUSTER CONTABILIDADE", Segment.OTHER],
  ["NAIARA BARBOSA FRANCO MARRA", Segment.HEALTH],
  ["DANIELA DIAS GONDIM", Segment.HEALTH],
  ["OMC - OFTALMO MEDICAL CENTER", Segment.HEALTH],
  ["OTICA LUZ", Segment.OTHER],
  ["CLIMA CLÍNICA DE DIAGNÓSTICO POR IMAGEM LTDA", Segment.HEALTH],
  ["JOSLEI DOS SANTOS", Segment.HEALTH],
  ["CASA CENTRO MEDICO", Segment.HEALTH],
  ["DANIELA TOLENTINO PARO", Segment.HEALTH],
  ["MARIA CRISTINA DA SILVA", Segment.HEALTH],
  ["CIDA DE OLIVEIRA ROSA (CIDA BANHO E TOSA)", Segment.PET],
  ["ELLEN CRISTINA CAMPOS SILVA (PET DA MEL)", Segment.PET],
  ["KAMILA PINHEIRO", Segment.PET],
  ["BIODIAGNÓSTICO", Segment.HEALTH],
  ["BANHO& TOSA SPA DOKÃO", Segment.PET],
  ["CLINICA VIVER ASSESSORIA E SERVIÇOES LTDA", Segment.HEALTH],
  ["ISO OLHOS", Segment.HEALTH],
  ["CLÍNICA MEDGEN", Segment.HEALTH],
  ["CHECKUP LABORATORIOS", Segment.HEALTH],
  ["RM RESSONÂNCIA", Segment.HEALTH],
  ["AGRODEZ SEGISMUNDO", Segment.PET],
  ["ELO IMAGEM", Segment.HEALTH],
  ["Banho e tosa meu melhor amigo", Segment.PET],
  ["Dr Adalton Junior", Segment.HEALTH],
  ["PAULO HENRIQUE DE FREITAS VET", Segment.PET],
  ["HCO", Segment.HEALTH],
  ["CDI", Segment.HEALTH],
  ["ARNALDO MACHADO BORGES DO VALE ( OFTALMOLOGISTA)", Segment.HEALTH],
  ["larissa vet", Segment.PET],
  ["ARTUR BENTO DE FARIA", Segment.PET],
  ["IMAGENS MEDICAS LTDA", Segment.HEALTH],
  ["GARDEN FLORES LTDA", Segment.HOME],
  ["LENA PET SHOP", Segment.PET],
  ["BRUTUS BATERIAS", Segment.AUTO],
  ["UBERCLIN SERVIÇOS MÉDICOS LTDA", Segment.HEALTH],
  ["LIDI PET SHOP (LIDIANE ROSA DE FREITAS)", Segment.PET],
  ["AQUI GAS", Segment.HOME],
  ["PET WAY", Segment.PET],
  ["ANNYELLE ALMEIDA MARCELINO- VITALITY PET", Segment.PET],
  ["PET E TRECOS", Segment.PET],
  ["CLINICA ATIVA", Segment.HEALTH],
  ["Cristiane Pereira Estética", Segment.HEALTH],
  ["JOÃO PAULO GONTIJO DE DEUS (VETERINÁRIO)", Segment.PET],
  ["via ÓTICA", Segment.OTHER],
  ["MARCIA SOARES HAIR", Segment.BEAUTY],
  ["VIVER BEM FARMA LTDA- COMPRE CERTO", Segment.HEALTH],
  ["MANANCIAL HIGIENIZAÇÃO E SANITIZAÇAO DE AMBIENTES", Segment.HOME],
  ["FIUZA PODOLOGIA", Segment.BEAUTY],
  ["HÉLIO GARCIA DE DEUS", Segment.PET],
  ["LABORATORIO CENTRAL DE ANÁLISES E PC LTDA", Segment.HEALTH],
  ["ÓTICA MATRIX", Segment.OTHER],
  ["CAMILA AMARAL SILVA", Segment.FITNESS],
  ["PREVENCOR UBERLANDIA", Segment.HEALTH],
  ["VIVA BEM PILATES UNIDADE 2", Segment.FITNESS],
  ["Nolasco Perfumaria", Segment.BEAUTY],
  ["Oral Cunha", Segment.HEALTH],
  ["Óticas Gouveia", Segment.OTHER],
  ["Pet Cuca – Alimentação Natural", Segment.PET],
  ["Plenamente – Psicologia e Desenvolvimento Humano", Segment.HEALTH],
  ["PrevenCardio", Segment.HEALTH],
  ["Saúde e Bem-Estar", Segment.HEALTH],
  ["CARDION (UBERLANDIA)", Segment.HEALTH],
  ["VERA LUCIA SILVA", Segment.PET],
  ["ESPAÇO TAO VIDA/ CRISTIANE", Segment.HEALTH],
  ["VITTA PILATES E FISIOTERAPIA", Segment.FITNESS],
  ["STUDIO DE PILATES JANAINA", Segment.FITNESS],
  ["ACADEMIA PUMPINGUP GYM", Segment.FITNESS],
  ["ACADEMIA ATIV LTDA", Segment.FITNESS],
  ["ANA KAROLINA NUTRICIONISTA", Segment.HEALTH],
  ["AUTO ESCOLA AZEVEDO", Segment.EDUCATION],
  ["RADIOCENTER", Segment.HEALTH],
  ["SILVIA BELICUAS", Segment.HEALTH],
  ["ACUNPUTURA E MAGNETOTERAPIA", Segment.HEALTH],
  ["CIA TEK SOLUÇOES EM INFORMATICA E ELETRONICOS", Segment.OTHER],
  ["THASSIA CAMILLA DANÇAS ORIENTAIS", Segment.FITNESS],
  ["ESPACO PAULA MATARAZZO", Segment.HEALTH],
  ["WORK BELLO MARMORARIA", Segment.HOME],
  ["DROGARIA MEGAMAIS FARMA", Segment.HEALTH],
  ["PET SHOP SUL", Segment.PET],
  ["PULSO CARDIOLOGIA", Segment.HEALTH],
  ["DIOGO KALLAS", Segment.HEALTH],
  ["MAIS SAUDE CUIDADOS ESPECIAIS AMBULANCIA", Segment.HEALTH],
  ["JULIANA FERREIRA SANTANA", Segment.HEALTH],
  ["LABORATÓRIO TRIANGULO", Segment.HEALTH],
  ["RAYANA OLIVEIRA PSICANALISTA", Segment.HEALTH],
  ["ARMAZEM DOS GRAOS", Segment.BEAUTY],
  ["LUCIA OLIVEIRA TERAPEUTA", Segment.HEALTH],
  ["FARMA VIP", Segment.HEALTH],
  ["EXATA VET", Segment.PET],
  ["Diana Flores e Presentes", Segment.HOME],
  ["MINAS TEC UDI", Segment.OTHER],
  ["PULMONAR COMERCIO DE EQUIPAMENTOS BIOMEDICOS LTDA", Segment.HEALTH],
  ["NUTRI JU NASCIMENTO", Segment.HEALTH],
  ["CAMILLA BORGES DE ARAUJO (NUTRICIONISTA)", Segment.HEALTH],
  ["UDI DOG ADESTRAMENTO", Segment.PET],
  ["RF VENDAS E ASSISTENCIA TECNICA", Segment.OTHER],
  ["Linzy Óptica - Loja M", Segment.OTHER],
  ["Luzoptica center LTDA", Segment.OTHER],
  ["DARLINE ALMEIDA MASSOTERAPEUTA", Segment.BEAUTY],
  ["PRISCILA APARECIDA BARBOSA (PSICOLOGA)", Segment.HEALTH],
  ["PETLAND", Segment.PET],
  ["ESPAÇO MAIS SAÚDE", Segment.HEALTH],
  ["BIO LAV", Segment.HOME],
  ["JULIANA FERREIRA SANTANA MASSOTERAPIA", Segment.BEAUTY],
  ["PET PRIME", Segment.PET],
  ["DR. FERNANDO CEZAR VAZ ANDREO", Segment.HEALTH],
  ["IZZA GAS EIRELI", Segment.HOME],
  ["DANIELY RODRIGUES SILVA", Segment.HEALTH],
  ["PONTAL NET", Segment.OTHER],
  ["ML PERSONALIZAÇÃO E BRINDES", Segment.OTHER],
  ["CHAVEIRO ROOSEVELT", Segment.HOME],
  ["DRI PAPELARIA", Segment.EDUCATION],
  ["MARCELO HAYECK", Segment.HEALTH],
  ["PAULO VINICIUS BORELA ( OTORRINO LARINGOLOGISTA)", Segment.HEALTH],
  ["SOS COMERCIO E SERVIÇOS LTDA M.E", Segment.OTHER],
  ["AUTO ELETRICA CENTRAL LTDA", Segment.HOME],
  ["RAFAEL HENRIQUE PSICOLOGO", Segment.HEALTH],
  ["Dra Vitória Silva de Oliveira", Segment.HEALTH],
  ["GRAZIELA DE CAIXETA E SILVA", Segment.HEALTH],
  ["HIDROFREIOS", Segment.AUTO],
  ["NUBIA CABELEREIRA", Segment.BEAUTY],
  ["NATALIA GUIMARAES MANICURE", Segment.BEAUTY],
  ["LUCYS BABY KIDS", Segment.BEAUTY],
  ["CLINICA MED. PSIQUI. DR MARCELO FREITAS QUEIROZ", Segment.HEALTH],
  ["DROGARIA ANDRADAS", Segment.HEALTH],
  ["DRI ESTETIC HAIR", Segment.BEAUTY],
  ["INSPIRIS STUDIO", Segment.FITNESS],
  ["AUTO CENTER JR COMERCIO LTDA", Segment.AUTO],
  ["ALINE PORFIRIO DA SILVA", Segment.BEAUTY],
  ["ESPAÇO DILCE HAIR", Segment.BEAUTY],
  ["DAMIS TREINAMENTOS", Segment.EDUCATION],
  ["PNEUMOCLINICA SERVIÇOS MEDICOS", Segment.HEALTH],
  ["LABORFOTO", Segment.OTHER],
  ["DROGARIA AMELIA SILVA LTDA", Segment.HEALTH],
  ["ACTION INFORMATICA", Segment.OTHER],
  ["STREET GAMES", Segment.OTHER],
  ["KARLA VIEIRA _ NAILS", Segment.BEAUTY],
  ["CLINICA DONI", Segment.HEALTH],
  ["GRAZIELLE DERMATOLOGISTA", Segment.HEALTH],
  ["CLAUDIA PEREIRA RODRIGUES", Segment.BEAUTY],
  ["CHAVEIRO E CARIMBO AFONSO PENA", Segment.HOME],
  ["PAULO CESAR BANHO E TOSA", Segment.PET],
  ["ATELIE DOS PETS", Segment.PET],
  ["ESTETICAO", Segment.PET],
  ["VILLA VET", Segment.PET],
  ["EULALIA ESTETICA SALÃO", Segment.BEAUTY],
  ["PET E BARROS", Segment.PET],
  ["COMFORT CENTER", Segment.HOME],
  ["DONA MEIRA ESMALTERIA", Segment.BEAUTY],
  ["AGROPET DOG CAT", Segment.PET],
  ["Doutores das Crianças", Segment.HEALTH],
  ["VITALITY PET", Segment.PET],
  ["JULIENE CRISTINA SILVERIO MAIA (VETERINARIA)", Segment.PET],
  ["RF Serralheria", Segment.HOME],
  ["Conrado Lopes Advocacia", Segment.OTHER],
  ["Psicologa Maria José", Segment.HEALTH],
  ["VET 4 LIFE", Segment.PET],
  ["BEETOOLS ESCOLA DE IDIOMA", Segment.EDUCATION],
  ["Farma Nossa", Segment.HEALTH],
  ["ODONTO COMPANY AEROPORTO", Segment.HEALTH],
  ["SHOPPING DOS ANIMAIS", Segment.PET],
  ["IARA FERREIRA ALVES", Segment.BEAUTY],
  ["LA VIE VETERINÁRIA", Segment.PET],
  ["Dob pet Shop", Segment.PET],
  ["AGRO E CIA", Segment.PET],
  ["Spaço D’ Eles", Segment.PET],
  ["CAMILA DA COSTA PIRES", Segment.HEALTH],
  ["DRIVE PET", Segment.PET],
  ["RONIVANIA COELHO (VETERINARIA)", Segment.PET],
  ["HELOVET", Segment.PET],
  ["GABRIELA SANTOS CARVALHO (VETERINARIA)", Segment.PET],
  ["ANA CRISTINA DA CRUZ SILVA (DERMATOLOGISTA)", Segment.HEALTH],
  ["ARTHA ALIMENTAÇÃO ANIMAL", Segment.PET],
  ["HERNIA MED CENTER (CLINICA MEDICA)", Segment.HEALTH],
  ["HEITOR LUIZ (CIRURGIA GERAL E BARIATRICA)", Segment.HEALTH],
  ["ROBLEDO VITORINO (PSIQUIATRA)", Segment.HEALTH],
  ["ALESSANDRA RESENDE OLIVEIRA CARNEIRO", Segment.HEALTH],
  ["ODONTO COMPANY GRAMADO", Segment.HEALTH],
  ["ROGERIO RUFINO DE VASCONCELOS (DENTISTA)", Segment.HEALTH],
  ["FISIOTERAPIA NELSON PORTO", Segment.HEALTH],
  ["AMOR EM PATAS ESTETICA ANIMAL", Segment.PET],
  ["DRA. RENATA", Segment.PET],
  ["VILMA PEREIRA DA ROCHA (PODOLOGA)", Segment.BEAUTY],
  ["LARISSA MENDONÇA NEVES (PSICOLOGA)", Segment.HEALTH],
  ["FONTES ODONTOLOGIA EIRELI", Segment.HEALTH],
  ["LINNY PET SHOP", Segment.PET],
  ["CLINICA/STUDIO VIVERDE", Segment.FITNESS],
  ["CENTER ODONTOLOGIA EIRELI", Segment.HEALTH],
  ["MULTIIMAGEM CLINICA DIAGNOSTICO", Segment.HEALTH],
  ["INDER (CLINICA MEDICA)", Segment.HEALTH],
  ["MULTICLÍNICA", Segment.HEALTH],
  ["DR. ANDRESSA GERIATRA", Segment.HEALTH],
  ["AMIGOS DO CORAÇAO CLINICA", Segment.HEALTH],
  ["L´EQUIPE CLINICA INTEGRADA MATRIZ", Segment.HEALTH],
  ["DR. RODRIGO RODRIGUES UROLOGISTA", Segment.HEALTH],
  ["VALMIR GERALDO COSTA", Segment.HEALTH],
  ["CLINCA EMAGRECENTRO UBERLÂNDIA", Segment.BEAUTY],
  ["CLINICA ARRITIMIAS", Segment.HEALTH],
  ["LA DERME (CLINICA MÉDICA)", Segment.HEALTH],
  ["SERMED POLICLINICA", Segment.HEALTH],
  ["REABILITÁ (CLINICA MEDICA)", Segment.HEALTH],
  ["DRA. VERONICA", Segment.HEALTH],
  ["DRA. RANYELLI SOUZA", Segment.HEALTH],
  ["PROCORE (CLINICA MEDICA E CARDIOLOGIA)", Segment.HEALTH],
  ["ESPAÇO IMAGEM VIDA (CLINICA)", Segment.HEALTH],
  ["ALINE REIS", Segment.HEALTH],
  ["PAULO VINICIUS BORELA", Segment.HEALTH],
  ["ALESSANDRO RIBEIRO LEMOS", Segment.HEALTH],
  ["FONOCARE FONOAUDIOLOGIA LTDA", Segment.HEALTH],
  ["PERSONAL VET", Segment.PET],
  ["VIA GASTRO (clinica)", Segment.HEALTH],
  ["DR CRISTIANO MUNDIM DE OLIVEIRA", Segment.HEALTH],
  ["MEDCOR (clínica de cardiologia)", Segment.HEALTH],
  ["NEOOFTALMO (clinica de oftamologia)", Segment.HEALTH],
  ["PODOLOGA ZELIA SOUZA", Segment.BEAUTY],
  ["MARCOS GONÇALVES FERREIRA(CARDIOLOGISTA)", Segment.HEALTH],
  ["AGROPET CONQUISTA", Segment.PET],
  ["CLINICA GASPARIN LTDA", Segment.HEALTH],
  ["LUCAS SOUZA LIMA", Segment.FITNESS],
  ["DRA. LARISSA S. FOGAÇA", Segment.HEALTH],
  ["CLÍNICA ENDOVITA (CLÍNICA MÉDICA)", Segment.HEALTH],
  ["PODOLOGA ZENILDA", Segment.BEAUTY],
  ["DENISE VALADÃO", Segment.HEALTH],
  ["ROLEMBERG MARTINS", Segment.HEALTH],
  ["CLINICA NOSSO ENCONTRO", Segment.HEALTH],
  ["FONOREABILITY CLINICA DE FONOAUDIOLOGIA", Segment.HEALTH],
  ["AMI CLÍNICA (CLÍNICA MÉDICA)", Segment.HEALTH],
  ["CLÍNICA IMAGEM CENTRO DIAGNOSTICO", Segment.HEALTH],
  ["CLINICA DE ARRITMIAS DR FELIPE SOUZA", Segment.HEALTH],
  ["DRA. RAFAELA BERNARDES", Segment.HEALTH],
  ["DR. SANDRO BERALDO", Segment.HEALTH],
  ["DR GENES SILVESTRE OFTALMO", Segment.HEALTH],
  ["ICCU (INSTITUTO DO CRANIO E DA COLUNA)", Segment.HEALTH],
  ["Líbia Doces", Segment.FOOD],
  ["NOSSA OPTICA", Segment.OTHER],
  ["VALDOMIRO CABELEREIRO", Segment.BEAUTY],
  ["VITACARRE SAUDE DOMICILIAR LTDA", Segment.HEALTH],
  ["THUANNE MACHADO LIMA (VETERINARIA)", Segment.PET],
  ["DR LUCILIA SANTOS (CLINICA SANTA BERNADETE)", Segment.HEALTH],
  ["EL VIDA HOME CARE", Segment.HEALTH],
  ["QUINTINO TERAPEUTA", Segment.HEALTH],
  ["Thais Favato de Almeida", Segment.PET],
  ["LEONOR ALVES VIEIRA (PODOLOGA)", Segment.BEAUTY],
  ["ESPAÇO ESTETICO FERNANDA ANDRADE", Segment.BEAUTY],
  ["EUROSKIN ESTETICA LDTA", Segment.BEAUTY],
  ["ALINE KELI DE OLIVEIRA", Segment.HEALTH],
  ["SALUTE ASSISTENCIA MEDICA VETERINARIA", Segment.PET],
  ["ÓTICA ABSOLUTA", Segment.OTHER],
  ["DR. FRANCINE", Segment.HEALTH],
  ["OTOFACE UMC", Segment.HEALTH],
  ["STUDIO ALESSANDRA SANTOS", Segment.BEAUTY],
  ["IME CLÍNICA CIDADÃ", Segment.HEALTH],
  ["CARLA REIS MACHADO", Segment.HEALTH],
  ["CLINICA FLORESÇA ESTETICA", Segment.BEAUTY],
  ["RAQUEL PONTES (NUTRICIONISTA)", Segment.HEALTH],
  ["DRA. ALINE LOPES", Segment.HEALTH],
  ["CLINICA DRA. LARA MENDES", Segment.BEAUTY],
  ["LINDINHA COMESTICOS / ESTETICA", Segment.BEAUTY],
  ["ANA COSMÉTICOS", Segment.BEAUTY],
  ["DANIANE ESTETICISTA", Segment.BEAUTY],
  ["ARIANA ESTETICISTA", Segment.BEAUTY],
  ["CLINICA ORTOPEDICA SANTA CLARA", Segment.HEALTH],
  ["GUILHERME psico", Segment.HEALTH],
  ["CLINICA DOS OLHOS", Segment.HEALTH],
  ["Uai Makes - ISIS MENDES COSMETICOS", Segment.BEAUTY],
  ["BEM ESTAR .ECO", Segment.BEAUTY],
  ["CLINICA INSTITUTO CHIOATO- LUISA CHIOATO", Segment.HEALTH],
  ["ÓTICA NACIONAL", Segment.OTHER],
  ["VOCÊ ATLETA", Segment.BEAUTY],
  ["DR PATRICIA MENDONÇA VIEIRA", Segment.HEALTH],
  ["ADRIANA MARIA LIMA", Segment.OTHER],
  ["CLINICA MEDFONTES SERVIÇOS MEDICOS", Segment.HEALTH],
  ["OFTALMOCENTER", Segment.HEALTH],
  ["CLINICA SARAN E ARCIERI", Segment.HEALTH],
  ["Studio Evellyn Carmo", Segment.BEAUTY],
  ["BILU PAPELARIA", Segment.EDUCATION],
  ["CLINICA ESPACO BEM VIVER", Segment.HEALTH],
  ["FISIO CARE PET (CLINICA)", Segment.HEALTH],
  ["CDC CENTRO DERMATOLOGICO CIRURGICO", Segment.HEALTH],
  ["ANDREA JUSTINO ANDRADE (NUTRICIONISTA)", Segment.HEALTH],
  ["Paulo Cesar Rosa (PSICOLOGO)", Segment.HEALTH],
  ["RODRIGO COSMÉTICOS", Segment.BEAUTY],
  ["DRA. ANA JULIA RODRIGUES FERREIRA", Segment.HEALTH],
  ["REJANE FISIOTERAPIA PÉLVICA", Segment.HEALTH],
  ["DRA. LUDMILLA SANTOS SOARES BOAVENTURA", Segment.BEAUTY],
  ["Polly Bronze", Segment.BEAUTY],
  ["Ana Amélia Rodovalho", Segment.HEALTH],
  ["VALESKA MARQUES MACHADO", Segment.HEALTH],
  ["Academia Art Fisic", Segment.FITNESS],
  ["Marli Santos, estética corporal e facial", Segment.BEAUTY],
  ["CLÍNICA PHYSICAL", Segment.HEALTH],
  ["HOME CARE LUZ PARA VIDA", Segment.HEALTH],
  ["PSICOLOGA VITÓRIA ARANTES DE OLIVEIRA", Segment.HEALTH],
  ["CLINICA ESPAÇO EQUILÍBRIO", Segment.HEALTH],
  ["Tall lace", Segment.BEAUTY],
  ["OdontoCompany Tocantins", Segment.HEALTH],
  ["Clinica Cicatrizzare Uberlândia", Segment.HEALTH],
  ["RPA SOLUÇÕES ODONTOLÓGICAS", Segment.HEALTH],
  ["OdontoCompany Alvorada", Segment.HEALTH],
  ["MINHA MÉDICA DE FAMÍLIA", Segment.HEALTH],
  ["ieda Toscano", Segment.BEAUTY],
  ["INSTITUTO DHC DE PSICOLOGIA", Segment.HEALTH],
  ["Biovet Atendimento Veterinário", Segment.PET],
  ["Berbert MED", Segment.HEALTH],
  ["Catharina Somerlate Franco Tomich", Segment.HEALTH],
  ["GEROCARE", Segment.HEALTH],
  ["Priscilla Lassi Lozano De Faria Leocadio", Segment.HEALTH],
  ["Colina Pet Store", Segment.PET],
  ["SORRIX UBERLANDIA", Segment.HEALTH],
  ["Espaço terapêutico Deyniele Carvalho", Segment.HEALTH],
  ["Zonno Odontologia", Segment.HEALTH],
  ["Consultório Odontológico Adriano Barbosa", Segment.HEALTH],
  ["Ana Maria Leandro", Segment.PET],
  ["Bruna Morais Esteticista", Segment.BEAUTY],
  ["Clinica Core Fitness e Fisioterapia", Segment.HEALTH],
  ["OdontoCompany Aparecida", Segment.HEALTH],
  ["Eliana Alves Pereira", Segment.HEALTH],
  ["Tático Cão Pet Shop Movel", Segment.PET],
  ["Clínica de Fisioterapia Fábio Rezende", Segment.HEALTH],
  ["CS VET 24 HR", Segment.PET],
  ["Maina Tavares Zanoni", Segment.HEALTH],
  ["AMANDA MOURI", Segment.HEALTH],
  ["DROGARIA MAIS SAUDE", Segment.HEALTH],
  ["Sermed", Segment.HEALTH],
  ["J. S. de Oliveira Fonoaudiologia", Segment.HEALTH],
  ["Clínica Pratic Odonto", Segment.HEALTH],
  ["COMPRE CERTO AFONSO PENA", Segment.HEALTH],
  ["DRA. MARIA CLARA CARNEIRO", Segment.HEALTH],
  ["Industrial Farma", Segment.HEALTH],
  ["Gustavo Albuquerque Oftalmologia", Segment.HEALTH],
  ["PAPALEGUAS GAS E AGUA", Segment.HOME],
  ["SOL LAVANDERIA", Segment.HOME],
  ["Farma do trabalhador (MARTINS)", Segment.HEALTH],
  ["Marielle Freitas Contadora", Segment.OTHER],
  ["Marielle Freitas Nutricionista", Segment.HEALTH],
  ["Larissa Camilo Vieira Santos", Segment.HEALTH],
  ["VIVA BELLA COSMETICOS", Segment.BEAUTY],
  ["PHARMA POPULAR LTDA", Segment.HEALTH],
  ["Dra. Ana Paula palazzo Psi", Segment.HEALTH],
  ["Tatiane silva Rodrigues costa", Segment.BEAUTY],
  ["ESPACO HAPPY HOUR", Segment.BEAUTY],
  ["ODONTO VIP", Segment.HEALTH],
  ["PARK GÁS", Segment.HOME],
  ["Dra. Elineia Aparecida", Segment.HEALTH],
  ["DRA. DIANKELLE FARIA", Segment.HEALTH],
  ["Elviamara Silva dos Santos", Segment.HEALTH],
  ["DR. FÁBIO LEOCÁDIO", Segment.HEALTH],
  ["INSTITUTO NILMA GONZAGA", Segment.BEAUTY],
  ["DR. DANIEL JUNIOR", Segment.HEALTH],
  ["DRA. JEANNE MARTINS", Segment.HEALTH],
  ["DRA. PATRICIA BERNARDINO", Segment.HEALTH],
  ["DR. DANILO RODRIGUES", Segment.HEALTH],
  ["All Petz Vet e Pet", Segment.PET],
  ["Dra. PRISCILA BORGES", Segment.PET],
  ["DRA. CARINA CARLA", Segment.HEALTH],
  ["Clínica Infantil Desenvolver", Segment.HEALTH],
  ["DRA. GIOVANNA MARIANA NUTRI", Segment.HEALTH],
  ["Studio Yasmin Goncalves", Segment.BEAUTY],
  ["Papelaria Europa", Segment.EDUCATION],
  ["Drogaria Virtual Drugstore Eirelli", Segment.HEALTH],
  ["DRA. FERNANDA PESSOA", Segment.HEALTH],
  ["DRA. GABRIELA AMÂNCIO", Segment.HEALTH],
  ["DRA. LARISSA APARECIDA", Segment.HEALTH],
  ["Quiromagic", Segment.BEAUTY],
  ["Aline Luciana dos Santos", Segment.BEAUTY],
  ["Thais Souza Estética", Segment.BEAUTY],
  ["BENDITACOR E ESCOVAS EXPRESS", Segment.BEAUTY],
  ["DRA. LUCIANA CRISTINA", Segment.HEALTH],
  ["DRA. MARIANNE CARDOSO", Segment.HEALTH],
  ["Nathan Garcez", Segment.HEALTH],
  ["Clínica Demafit", Segment.HEALTH],
  ["Laryssa Mendes Keidalga", Segment.HEALTH],
  ["Janine Espaço de terapias", Segment.HEALTH],
  ["DRA. SILVANIA APARECIDA", Segment.HEALTH],
  ["Clinica Dra. Rackell medonça", Segment.HEALTH],
  ["DRA. THAIS MENDES", Segment.HEALTH],
  ["DRA. RENATA REZENDE LACERDA", Segment.HEALTH],
  ["Drogaria Teles", Segment.HEALTH],
  ["Drogaria Seleta", Segment.HEALTH],
  ["Climev- clinica medica veterinária 24 horas", Segment.PET],
  ["cross experience roosevelt", Segment.FITNESS],
  ["Farma trabalhador (MORUMBI)", Segment.HEALTH],
  ["Farma trabalhador (PLANALTO)", Segment.HEALTH],
  ["DRA. NAICE SOUZA ALVES", Segment.HEALTH],
  ["DRA. RENATA ALVES CARNEIRO", Segment.HEALTH],
  ["DRA. NICE CORRÊA MACHADO FONTES", Segment.HEALTH],
  ["Ipis- instituto de praticas integrativas em saude", Segment.HEALTH],
  ["Gabrielly isaac Rodrigues", Segment.BEAUTY],
  ["CLINICA INTERFISIO", Segment.HEALTH],
  ["Dra. Raquel Rozaria Fróis", Segment.HEALTH],
  ["Clinivet", Segment.PET],
  ["CLÍNICA CNF", Segment.HEALTH],
  ["CEPRO - IQO", Segment.HEALTH],
  ["Centro Educacional Greenleaf", Segment.EDUCATION],
  ["Oralmedic", Segment.HEALTH],
  ["CIOR", Segment.HEALTH],
  ["Art'nailsester (estetica)", Segment.BEAUTY],
  ["CLINICA MEDICA MAREDU", Segment.HEALTH],
  ["DR. KENNEDY RODRIGUES LIMA", Segment.BEAUTY],
  ["KATIA ALESSANDRA DE SOUZA CAETANO", Segment.HEALTH],
  ["ESPAÇO FLORESCER", Segment.HEALTH],
  ["SHEILA LIMA FISIOTERAPIA E PILATES", Segment.HEALTH],
  ["CTN Quiropraxia", Segment.BEAUTY],
  ["Dra. Carla Beatriz", Segment.PET],
  ["Ozana massoterapeuta", Segment.BEAUTY],
  ["ORALSPECIAL", Segment.HEALTH],
  ["DRA VICIVONE", Segment.HEALTH],
  ["skin life", Segment.BEAUTY],
  ["LABAC LABORATORIOS", Segment.HEALTH],
  ["COMPRE CERTO SARAIVA", Segment.HEALTH],
  ["COMPRE CERTO ROOSEVELT", Segment.HEALTH],
  ["Dr Herculano Ribeiro", Segment.HEALTH],
  ["PSICÓLOGA SANDRA DE PÁDUA", Segment.HEALTH],
  ["PSICÓLOGA ANA MARIA", Segment.HEALTH],
  ["PSICÓLOGA SELVINA RODRIGUES DE MELO", Segment.HEALTH],
  ["Daymaximino alongamentos", Segment.BEAUTY],
  ["THAYSE MENDES DENTISTA", Segment.HEALTH],
  ["Dr Filipe Gasparin", Segment.HEALTH],
  ["Gisele Aguiar Serviçoes", Segment.HEALTH],
  ["PSICÓLOGO JORDANO RAFAEL", Segment.HEALTH],
  ["ODONTO COMPANY CENTRO", Segment.HEALTH],
  ["ODONTO COMPANY VIP (SEGISMUNDO PEREIRA)", Segment.HEALTH],
  ["Rodrigo gás", Segment.HOME],
  ["ODONTO COMPANY GRANADA", Segment.HEALTH],
  ["ODONTO COMPANY ROOSEVELT", Segment.HEALTH],
  ["CLINICA MARILEUSA", Segment.HEALTH],
  ["Arthur Silveira Martins", Segment.HOME],
  ["Optica e relojoaria Rodrigues", Segment.OTHER],
  ["853 Barbearia", Segment.BEAUTY],
  ["FISIO E PILATES MRM", Segment.HEALTH],
  ["Clínica MDFamily", Segment.HEALTH],
  ["Meu Riso Clinica Odontologica", Segment.HEALTH],
  ["PSICÓLOGA YASMIN SILVA", Segment.HEALTH],
  ["ANDALLES FASHION", Segment.BEAUTY],
  ["RONIS FOTOGRAFIAS", Segment.OTHER],
  ["DISK AMOR E EMOÇOES", Segment.HOME],
  ["Plus motopecas", Segment.AUTO],
  ["PSICÓLOGA CINTIA REZENDE LIMA", Segment.HEALTH],
  ["Rejane optica", Segment.OTHER],
  ["ELAV LAVANDERIA", Segment.HOME],
  ["PSICÓLOGA ANA CÂNDIDA DE OLIVEIRA", Segment.HEALTH],
  ["PSICÓLOGA MAÍLA RIBEIRO", Segment.HEALTH],
  ["ÓTICA DIAMANTE ROSA", Segment.OTHER],
  ["Uberoticas", Segment.OTHER],
  ["Karla Esteves estetica das unhas", Segment.BEAUTY],
  ["Lu flor Nails", Segment.BEAUTY],
  ["Udicor Gestão em Saúde", Segment.HEALTH],
  ["Psicologo Guilherme Fernandes", Segment.HEALTH],
  ["Expansão do ser", Segment.HEALTH],
  ["DRA. JANAINA DA COSTA", Segment.HEALTH],
  ["INSITUTO DOS OLHOS DO TRIANGULO", Segment.HEALTH],
  ["Priscila Martins Dias", Segment.HEALTH],
  ["Ultrafeto Ultrassonografia", Segment.HEALTH],
  ["Oliver Advocacia", Segment.OTHER],
  ["Davi Psicologia", Segment.HEALTH],
  ["AGRO GERAIS", Segment.PET],
  ["MEDITA MINDFULNESS", Segment.HEALTH],
  ["PSICANALISTA VALÉRIA CRISTINA", Segment.HEALTH],
  ["ANA LUIZA PEIXOTO", Segment.HEALTH],
  ["Venancio estetica", Segment.BEAUTY],
  ["DRA. SABRINA ALVIM", Segment.HEALTH],
  ["ESTÉTICA UBERLANDIA", Segment.BEAUTY],
  ["Caroline Cristina Carvalho Psicologa infantil", Segment.HEALTH],
  ["Debora Araujo Psicologa", Segment.HEALTH],
  ["Insight Clínica - Liana Carvalho", Segment.HEALTH],
  ["Dentistas do trabalhador - Floriano Peixoto", Segment.HEALTH],
  ["Dra. Fabiane Peres", Segment.HEALTH],
  ["MR Menina rica", Segment.BEAUTY],
  ["Dentistas do trabalhador - Coronel Antônio Alves", Segment.HEALTH],
  ["Dra. Juliana carolina", Segment.HEALTH],
  ["Espaço integrativo pet", Segment.PET],
  ["Otica da praca", Segment.OTHER],
  ["Nadia Bouzas", Segment.HEALTH],
  ["Via pilates", Segment.FITNESS],
  ["Clinica Barbosa e Marra", Segment.HEALTH],
  ["Camila nails designer", Segment.BEAUTY],
  ["DIENIELLE FREITAS CARDOSO", Segment.HEALTH],
  ["Ime clinica cidadã - oftalmologia", Segment.HEALTH],
  ["CASA E", Segment.HEALTH],
  ["RPI Servicos express", Segment.HOME],
  ["Andréa Fest", Segment.OTHER],
  ["Fine Eletrics", Segment.HOME],
  ["New Cicle Motos", Segment.AUTO],
  ["Dra. Luciana Nunes", Segment.HEALTH],
  ["Jaguar Gás", Segment.HOME],
  ["DR Hydra encanador", Segment.HOME],
  ["LF elétrica", Segment.HOME],
  ["DÁDIMA", Segment.HEALTH],
  ["TERAPEUTA DÁDIMA GUIA", Segment.HEALTH],
  ["PSICÓLOGA THAYSA FERNANDA MARINHO", Segment.HEALTH],
  ["Aline barros psicologa", Segment.HEALTH],
  ["Dulcineia Souza terapia", Segment.HEALTH],
  ["DRA. JANICE EUGÊNIA", Segment.HEALTH],
  ["Fisioterapia Pelvica", Segment.HEALTH],
  ["Elétrica udi", Segment.HOME],
  ["CAST Odontologia", Segment.HEALTH],
  ["Albert Chaster dançaterapia", Segment.FITNESS],
  ["Animalife hospital veterinario 24 hr", Segment.PET],
  ["Gisele Podologa", Segment.BEAUTY],
  ["LABORATÓRIO PATOLÓGICO EDUARDO MINEIRO", Segment.HEALTH],
  ["SORRIA BEM MELHOR", Segment.HEALTH],
  ["Humanize Odonto", Segment.HEALTH],
  ["Raquel Podologia", Segment.BEAUTY],
  ["Gracielle Morais Fonaudiologia", Segment.HEALTH],
  ["Espaco Ro Bronze", Segment.BEAUTY],
  ["Nutricionista Brenda Oliveira", Segment.HEALTH],
  ["JULIANA OLIVEIRA MENDONÇA DE MOURA", Segment.HEALTH],
  ["Mileny Costa", Segment.HEALTH],
  ["Studio Life pilates", Segment.HEALTH],
  ["Mundo das Chaves", Segment.HOME],
  ["VLADEMIR MENDES SILVA", Segment.HEALTH],
  ["Drogao extra popular", Segment.HEALTH],
  ["NOVA VIDA FARMÁCIA", Segment.HEALTH],
  ["Elaine Machado", Segment.PET],
  ["DOGTOR VET", Segment.PET],
  ["JESSICA NUTRICIONISTA", Segment.HEALTH],
  ["GUSTAVO ERNESTO PSICOLOGO", Segment.HEALTH],
  ["Dr Paulo Henrique Vilela Amui", Segment.HEALTH],
  ["Home pet uberlandia", Segment.PET],
  ["Marcella Silva", Segment.PET],
  ["Francisco Kenji", Segment.HEALTH],
  ["florescer dourado", Segment.HEALTH],
  ["SP Doces e Delicias", Segment.FOOD],
  ["Espaço Jose Lamanes", Segment.BEAUTY],
  ["KAMILLA CAROLINA SILVA LIMA", Segment.HEALTH],
  ["Restart Segurança eletronica", Segment.HOME],
  ["SANDY BORGES NUTRI", Segment.HEALTH],
  ["Douglas Camargo - Microfisioterapia", Segment.HEALTH],
  ["Dra jacqueline Lima", Segment.HEALTH],
  ["CINTIA REGINA ALESSANDRI PSICOTERAPIA", Segment.HEALTH],
  ["THAIS GONÇALVES FIRMES", Segment.HEALTH],
  ["Barbosa Naturalis", Segment.HEALTH],
  ["Thalisia Geovanna Lagares", Segment.PET],
  ["Bruno Marinho S. M. Alves", Segment.HEALTH],
  ["Camila Oliveira", Segment.HEALTH],
  ["PALHARES PSICOLOGIA", Segment.HEALTH],
  ["ADALMIR PSICOLOGIA", Segment.HEALTH],
  ["Christiane Andrade Neves Ferreira", Segment.HEALTH],
  ["Hotelaria Dubi", Segment.PET],
  ["ANA PAULA LIMA PEREIRA", Segment.HEALTH],
  ["CEOMED- CENTRO DE OTORRINOLARINGOLOGIA", Segment.HEALTH],
  ["House Pet estetica Animal", Segment.PET],
  ["GESSILAINE ALMEIDA BESSA", Segment.HEALTH],
  ["ANA FLAVIA NUTRI", Segment.HEALTH],
  ["IRIS APARECIDA PSICOTERAPEUTA", Segment.HEALTH],
  ["MARIA JULIA ROCHA FERREIRA", Segment.HEALTH],
  ["Marilia Parreira Teixeira Arantes", Segment.HEALTH],
  ["Bioestitics e Biomedicina estetica", Segment.HEALTH],
  ["R T ODONTOLOGIA", Segment.HEALTH],
  ["DR. RAFAEL DRIGO PEIXOTO", Segment.HEALTH],
  ["CRICIANE BARBOSA SALES", Segment.HEALTH],
  ["Andreyna Nobrega", Segment.HEALTH],
  ["Dra Ana Carolina Damião Araújo", Segment.HEALTH],
  ["Vera Lucia da Silva Pontes", Segment.HEALTH],
  ["PAULO CESAR ALVES ROCHA", Segment.OTHER],
  ["Débora Soares Carvalho", Segment.HEALTH],
  ["Carolina Vasconcelos Psicóloga", Segment.HEALTH],
  ["Amanda Gomes de Souza", Segment.HEALTH],
  ["Espaço Terapeutico", Segment.HEALTH],
  ["Larissa Cardoso", Segment.HEALTH],
  ["Global Garden", Segment.HOME],
  ["FERNANDO HENRIQUE VELOSO PEDIATRA", Segment.HEALTH],
  ["ANA CAROLINA BARBOSA TORMENA", Segment.PET],
  ["ESTÁCIO LARANJEIRAS", Segment.EDUCATION],
  ["Farmacia Pague Menos", Segment.HEALTH],
  ["ESTÁCIO PLANALTO", Segment.EDUCATION],
  ["Doctor Feet", Segment.BEAUTY],
  ["Clinica OrtoDoctor", Segment.HEALTH],
  ["GISELE FARIA SILVA MOTTA ESTÉTICA", Segment.BEAUTY],
  ["Buffet Na Mesa Cakes", Segment.FOOD],
  ["Affetto psicologia", Segment.HEALTH],
  ["Costa Eventos e Viagens", Segment.LEISURE],
  ["Personal Vet Udi", Segment.PET],
  ["LEYA SANTOS ESTETICA", Segment.BEAUTY],
  ["Renove studio de pilates", Segment.FITNESS],
  ["Espaço Galaxy Massoterapia", Segment.BEAUTY],
  ["Flavia Mirelle Vilela Assis", Segment.HEALTH],
  ["Toda plena saúde e estética", Segment.BEAUTY],
  ["Sol de verão bronzeamento natural", Segment.BEAUTY],
  ["Monica Correia dos santos", Segment.BEAUTY],
  ["Aline Sicari", Segment.HEALTH],
  ["Tássio Silva Neiva", Segment.BEAUTY],
  ["Ana Lucia Massoterapeuta", Segment.BEAUTY],
  ["Amor com recheio", Segment.FOOD],
  ["Doces da Lua", Segment.FOOD],
  ["Espaço Camila Macedo", Segment.BEAUTY],
  ["JR ESTETICA AUTOMOTIVA", Segment.AUTO],
  ["Joel Rogerio Heitor Filho", Segment.HEALTH],
  ["Alcateia Ecotur", Segment.LEISURE],
  ["Hotel Escola Sorriso da Criança", Segment.EDUCATION],
  ["Studio Jady Migliatti", Segment.BEAUTY],
  ["HOBBY BURGER", Segment.FOOD],
  ["Hellen Costa Designer", Segment.BEAUTY],
  ["PEDRO DA SILVA ARAUJO BURLA", Segment.HEALTH],
  ["ÉLICA DE SOUZA BARBOSA", Segment.BEAUTY],
  ["Pollyarts Personalizados", Segment.OTHER],
  ["DONA ÓTICA", Segment.OTHER],
  ["Erica Pinheiro estetica avançada", Segment.BEAUTY],
  ["Uniestamp", Segment.OTHER],
  ["Clínica Zandaka", Segment.BEAUTY],
  ["Psicóloga Wanessa Monteiro", Segment.HEALTH],
  ["Cross Experience Alto Umuarama", Segment.FITNESS],
  ["JA - Juliett Angellis Estetica", Segment.BEAUTY],
  ["LAIS AVLIS ESTETICA FACIAL", Segment.BEAUTY],
  ["Personalize-se Produtos Personalizados", Segment.OTHER],
  ["Imperial Salão de Eventos", Segment.OTHER],
  ["Summer Pet", Segment.PET],
  ["Saude dos pés", Segment.BEAUTY],
  ["BIOESTETIC (DAYANNE DA ROCHA)", Segment.BEAUTY],
  ["Nova imagem", Segment.AUTO],
  ["Park Education Praça Paris", Segment.EDUCATION],
  ["STYLLO CALCADOS", Segment.BEAUTY],
  ["Lava jato calabria confiança", Segment.AUTO],
  ["Ponto fitness.", Segment.FITNESS],
  ["Andrea Alves Semijoias", Segment.BEAUTY],
  ["Fernanda Guimarães designer", Segment.BEAUTY],
  ["Juliana Miranda Braz", Segment.HEALTH],
  ["Brechó Villamil", Segment.BEAUTY],
  ["Otica tronconi", Segment.OTHER],
  ["LORRAINE BEAUTY", Segment.BEAUTY],
  ["KETELIN ESTÉTICA", Segment.BEAUTY],
  ["DESTAQUE MODAS", Segment.BEAUTY],
  ["THAYS COSMESTICOS", Segment.BEAUTY],
  ["Açucareiro Ateliê de Bolos", Segment.FOOD],
  ["Vitá Centro Odontologico", Segment.HEALTH],
  ["Estúdio Jô Ávila", Segment.BEAUTY],
  ["lava jato do neném", Segment.AUTO],
  ["Spaço Depillare", Segment.BEAUTY],
  ["Mumu pudicup", Segment.FOOD],
  ["Paulo Carvalho Filho", Segment.HEALTH],
  ["sofa lave", Segment.HOME],
  ["Ordones higienizaçao", Segment.HOME],
  ["Dra Geovana Cruz", Segment.HEALTH],
  ["WN Personalizados", Segment.OTHER],
  ["Personalizados Dline", Segment.OTHER],
  ["Junior express", Segment.HOME],
  ["LIBERTÉ FISIOTERAPIA E PILATES", Segment.HEALTH],
  ["GEOVANNA FONSECA COSTA", Segment.HEALTH],
  ["ALEXANDRE DOS SANTOS LOPES", Segment.FOOD],
  ["EVANI LUZIA ESTÉTICA", Segment.BEAUTY],
  ["ESPAÇO KARITA SANTOS", Segment.BEAUTY],
  ["Marcella Beatriz Moreira Cunha", Segment.HEALTH],
  ["Perfil da beleza uberlandia", Segment.BEAUTY],
  ["Carolina Nogueira studio", Segment.EDUCATION],
  ["Fisiolar Home Care", Segment.HEALTH],
  ["PAPELARIA COSMOS", Segment.EDUCATION],
  ["Paraiso Studio Beauty", Segment.BEAUTY],
  ["Brenda Marques Nutricionista", Segment.HEALTH],
  ["QUALIFISIO", Segment.HEALTH],
  ["Tia Karine odontologia infantil", Segment.HEALTH],
  ["EL SHADAY", Segment.BEAUTY],
  ["Designer Patrícia Roque", Segment.BEAUTY],
  ["Ranther Soares Fisioterapeuta", Segment.HEALTH],
  ["Dra . Meire Hellen Nunes", Segment.HEALTH],
  ["HOT DOG MAE E FILHA", Segment.FOOD],
  ["A LIGA", Segment.BEAUTY],
  ["Instituto do Sangue", Segment.HEALTH],
  ["Psicólogo Paulo Abbiati", Segment.HEALTH],
  ["Studio Adrielly Rezende", Segment.BEAUTY],
  ["Lavínia Borges nutrição esportiva", Segment.HEALTH],
  ["Juliana Macedo Pena Vogel", Segment.HEALTH],
  ["IAG - INSTITUTO DE ANGIOLOGIA", Segment.HEALTH],
  ["Coife Odonto Uberlândia", Segment.HEALTH],
  ["Studio Beauty Laura Ribeiro", Segment.BEAUTY],
  ["Juliana Freitas Chiareto", Segment.HEALTH],
  ["Lo Organiza", Segment.HOME],
  ["Espaço Letícia Neves", Segment.BEAUTY],
  ["Studio Vanessa Campos", Segment.BEAUTY],
  ["NAYARA ROSA", Segment.BEAUTY],
  ["Studio Tatiane Morais", Segment.BEAUTY],
  ["HDLAVY estética em estofados", Segment.HOME],
  ["InteliGentes Neuroaprendizagem", Segment.HEALTH],
  ["Paula Aparecida Almeida Silva", Segment.HEALTH],
  ["Maria Fernanda Psicopedagoga", Segment.HEALTH],
  ["Fernanda Nascimento", Segment.HEALTH],
  ["Clínica BIOESTHETICS", Segment.BEAUTY],
  ["A LINDA MODA FITNESS", Segment.FITNESS],
  ["Nutricionista Fabianne Guimarães", Segment.HEALTH],
  ["CREDITO ELITE", Segment.AUTO],
  ["PATRICIA GOUVEIA ROUPAS", Segment.BEAUTY],
  ["Nadia Maria Enfermeira", Segment.HEALTH],
  ["Espaço Leoa Bronze L.", Segment.BEAUTY],
  ["Clube Pet", Segment.PET],
  ["ALINE VIAGENS E TURISMO", Segment.LEISURE],
  ["Nutricionista Natália Vieira", Segment.HEALTH],
  ["MISTER MULTAS UBERLÂNDIA", Segment.OTHER],
  ["CLINICA SORRIFÁCIL", Segment.HEALTH],
  ["Jheovanna Braga", Segment.BEAUTY],
  ["La Di Caramelle", Segment.FOOD],
  ["Studio Leka Makeup Beauty", Segment.BEAUTY],
  ["Esplêndido Sabor Doceria", Segment.FOOD],
  ["VANESSA NAIL DESIGNER", Segment.BEAUTY],
  ["JTB PSICOLOGA", Segment.HEALTH],
  ["Corpille Medicina Estética", Segment.BEAUTY],
  ["CONTABILIZARBR CONTABILIDADE LTDA", Segment.OTHER],
  ["Bruna Marques Nail Designer", Segment.BEAUTY],
  ["JACQUELINE CARVALHO ESPAÇO", Segment.BEAUTY],
  ["WAGNER LUIS PSICOLOGO", Segment.HEALTH],
  ["Vera Maria Beauty & Academy", Segment.BEAUTY],
  ["Dr. Marcos Hissato sakashita", Segment.HEALTH],
  ["Studio Danielle Cristina", Segment.BEAUTY],
  ["EGREGORA ESTÉTICA", Segment.BEAUTY],
  ["Daniel Guimarães Fotografia", Segment.OTHER],
  ["RAVENA PAPER", Segment.EDUCATION],
  ["PERSONAL GLASSES COMERCIO", Segment.OTHER],
  ["TRAINING LAB STUDIO", Segment.FITNESS],
  ["Ateliê das massas", Segment.FOOD],
  ["Centro Especializado em Oftalmologia", Segment.HEALTH],
  ["UP PILATES", Segment.FITNESS],
  ["STUDIO SOUL", Segment.FITNESS],
  ["Noemi Martins", Segment.BEAUTY],
  ["Valgma Soares - Massagem", Segment.BEAUTY],
  ["Valgma Turismo", Segment.LEISURE],
  ["Studio Yasmin Santos", Segment.BEAUTY],
  ["PET FOOD UBERLANDIA", Segment.PET],
  ["VIA S SEMIJÓIAS", Segment.BEAUTY],
  ["F VINHOS", Segment.FOOD],
  ["Disk Encanador", Segment.HOME],
  ["AMENDOA CORES", Segment.BEAUTY],
  ["CLÁUDIA QUEIROZ PERFUMES", Segment.BEAUTY],
  ["LOOKAFIT", Segment.FITNESS],
  ["Clínica Revitale", Segment.HEALTH],
  ["DRINKELARIA", Segment.BEAUTY],
  ["CFC RIBEIRO", Segment.EDUCATION],
  ["NB MOVEIS USADOS", Segment.HOME],
  ["Lidia Maria Nails Designer", Segment.BEAUTY],
  ["LUCIANA GIMENES MANICURES", Segment.BEAUTY],
  ["CLÍNICA LAILA LEMOS", Segment.HEALTH],
  ["LUISA BARROS ODONTOLOGIA", Segment.HEALTH],
  ["MORDIDA DAS GALAXIAS", Segment.FOOD],
  ["REMODULAR ESPAÇO INTEGRADO", Segment.HEALTH],
  ["Studio Maria Clara", Segment.BEAUTY],
  ["MARA PRESENTES", Segment.BEAUTY],
  ["Ana Carolina Studio hair", Segment.BEAUTY],
  ["ESPACO DCASA", Segment.HOME],
  ["SPEED CAR LTDA", Segment.AUTO],
  ["Psicóloga Jéssica Fernandes", Segment.HEALTH],
  ["Esfera Sports", Segment.FITNESS],
  ["KATRICY ACESSÓRIOS", Segment.BEAUTY],
  ["Shangril-La Acupuntura", Segment.HEALTH],
  ["GLAM BEAUTY by ANNA MEDEIROS", Segment.BEAUTY],
  ["Dress Atelie Eliane Souza", Segment.BEAUTY],
  ["Renovare Stúdio", Segment.BEAUTY],
  ["Adriana de Oliveira de Paula", Segment.BEAUTY],
  ["DRA. FERNANDA LORENA", Segment.HEALTH],
  ["FITO + NATURE SUPLEMENTOS", Segment.BEAUTY],
  ["3S DESIGN", Segment.OTHER],
  ["Anna Eduarda lash designer", Segment.BEAUTY],
  ["HUMANIZA ODONTOLOGIA", Segment.HEALTH],
  ["Giovanna Castro Nails", Segment.BEAUTY],
  ["Daniela Oliveira esteticista", Segment.BEAUTY],
  ["KATIUCE PSICOLOGIA", Segment.HEALTH],
  ["EL CAPO BARBER CLUB", Segment.BEAUTY],
  ["Seu bronze", Segment.BEAUTY],
  ["Anny Gabriele designer", Segment.BEAUTY],
  ["ROSA TURQUESA", Segment.BEAUTY],
  ["PEDRO TERAPEUTA", Segment.HEALTH],
  ["Oca Arquitetura", Segment.HOME],
  ["Bia Studio", Segment.BEAUTY],
  ["Excelência Acompanhante Hospitalar", Segment.HEALTH],
  ["Fernanda Arantes Dornelos de Souza", Segment.HEALTH],
  ["BTD DRONES FILMAGENS", Segment.OTHER],
  ["Vivian Bandeira Santos", Segment.HEALTH],
  ["Instituto de Atenção a Sáude", Segment.HEALTH],
  ["Três Marias Personalizados", Segment.OTHER],
  ["Pratic Odonto - Aparecida", Segment.HEALTH],
  ["Pratic Odonto - Centro", Segment.HEALTH],
  ["Clínica Soma Sáude", Segment.HEALTH],
  ["3M CHAVEIRO 24HORAS", Segment.HOME],
  ["Mana Semi Joias", Segment.BEAUTY],
  ["Dayane Almeida | Psicocóloga", Segment.HEALTH],
  ["Clínica Psicológica Cleiton Rodrigues", Segment.HEALTH],
  ["IGREEN ENERGY", Segment.HOME],
  ["FJMÉDICA", Segment.HEALTH],
  ["Eli Bolos", Segment.FOOD],
  ["Dra. Mayara Cruvinel", Segment.HEALTH],
  ["Cíntia Alessandri", Segment.HEALTH],
  ["Juliana Palazzo", Segment.HEALTH],
  ["Segredos da beleza", Segment.BEAUTY],
  ["Ludiane Psicóloga", Segment.HEALTH],
  ["Escutas Psicologia e Psicanálise", Segment.HEALTH],
  ["Baroni", Segment.BEAUTY],
  ["Bianka Carvalho", Segment.HEALTH],
  ["Xandão Personal Trainer", Segment.FITNESS],
  ["Manuh Cestas e Mimo", Segment.OTHER],
  ["Fábio Alcântara", Segment.BEAUTY],
  ["Clinica Seguir Espaço Terapêutico", Segment.HEALTH],
  ["ROSA LAURA MODA E ACESSORIOS", Segment.BEAUTY],
  ["Psicólogo Teullys Marques", Segment.HEALTH],
  ["Universo Azul Intervenções ABA", Segment.HEALTH],
  ["CK English", Segment.EDUCATION],
  ["Luz & Art Nails", Segment.BEAUTY],
  ["Plenamente", Segment.HEALTH],
  ["LOJA OMEGA", Segment.BEAUTY],
  ["ZZ BARBA BRAVA", Segment.BEAUTY],
  ["UNITRANSITTO", Segment.EDUCATION],
  ["Pâmela Alves Psicóloga", Segment.HEALTH],
  ["Equipe Hair e Estética", Segment.BEAUTY],
  ["UAI ESTACIONAMENTO", Segment.AUTO],
  ["Casa das Cenas Escola de Psicodrama", Segment.HEALTH],
  ["REPARO SERVICE", Segment.HOME],
  ["Pillar Gente e Gestão", Segment.HEALTH],
  ["Psicóloga Camila Maria", Segment.HEALTH],
  ["ROSI BEAUTY NAILS", Segment.BEAUTY],
  ["MAGNO SUPLEMENTOS", Segment.HEALTH],
  ["BERÇARIO E ESCOLA PINGO D GENTE", Segment.EDUCATION],
  ["Tatiane Costa psicóloga", Segment.HEALTH],
  ["Atêlie Ferreira Matos", Segment.BEAUTY],
  ["Estilo’s Make", Segment.BEAUTY],
  ["INOVATI CARE", Segment.HEALTH],
  ["R A Clinicas Odontologicas", Segment.HEALTH],
  ["Consultório de Psicologia Fabrícia", Segment.HEALTH],
  ["Mybelle unhas e sobrancelhas", Segment.BEAUTY],
  ["INFINITAMENTE SUCESSO", Segment.EDUCATION],
  ["CLINICA DE OLHOS VALENTIM", Segment.HEALTH],
  ["Patrícia Faria Neuropsicológa", Segment.HEALTH],
  ["Psicóloga Joana Costa", Segment.HEALTH],
  ["Nutricionista Jessica Pereira", Segment.HEALTH],
  ["PSICOLOGA MARA LOPES", Segment.HEALTH],
  ["Jeniffer Ramos Nutricionista", Segment.HEALTH],
  ["Nutricionista Reila Satel", Segment.HEALTH],
  ["Espaço Tatiane Andrade", Segment.BEAUTY],
  ["Plena odontologia especializada", Segment.HEALTH],
  ["Bruna Cunha - Psicóloga", Segment.HEALTH],
  ["TRANSFORM ENERGY", Segment.HOME],
  ["Renata Nicurgo Psicologia", Segment.HEALTH],
  ["Letícia Santos Psicóloga", Segment.HEALTH],
  ["Psicóloga Polyana Dantas", Segment.HEALTH],
  ["Studio Karen Borges", Segment.BEAUTY],
  ["Psicóloga Jucélia Rocha", Segment.HEALTH],
  ["JR ESTUDIO BEAUTIFUL QUEEN", Segment.BEAUTY],
  ["RYAN NAILS PODOLOGO", Segment.BEAUTY],
  ["CONSULTORIA EM PROTEÇÃO VEICULAR", Segment.AUTO],
  ["Thaís Belafonte | Psicóloga", Segment.HEALTH],
  ["TJ TRANSPORTE ESCOLAR", Segment.AUTO],
  ["Pranamor - Terapias Energeticas", Segment.HEALTH],
  ["Aline Andrade | Psicóloga", Segment.HEALTH],
  ["4hands", Segment.EDUCATION],
  ["Oral S", Segment.HEALTH],
  ["Eliete Nascimento Nutricionista", Segment.HEALTH],
  ["Psicóloga Kamylla Arantes", Segment.HEALTH],
  ["CLINICA HARMONIA MENTAL", Segment.HEALTH],
  ["AMANDA AMORIM", Segment.BEAUTY],
  ["CAFE CARAMELO UBERLANDIA", Segment.FOOD],
  ["SOLIDES BENEFICIOS", Segment.AUTO],
  ["Psicóloga Maíra Michele", Segment.HEALTH],
  ["Adriane Alves - Psicóloga", Segment.HEALTH],
  ["DR. PEDRO DE ARAÚJO", Segment.HEALTH],
  ["MUSA FITNESS", Segment.FITNESS],
  ["STUDIO DS DANUBIA SILVA", Segment.BEAUTY],
  ["PSICÓLOGO JOÃO HUGO", Segment.HEALTH],
  ["Apolo Serviços Médicos", Segment.HEALTH],
  ["Belas Unhas da Dany", Segment.BEAUTY],
  ["Ninalô Cosméticos", Segment.BEAUTY],
  ["Psicóloga Nathalia Arantes", Segment.HEALTH],
  ["LUCAS PARERA PHOTO E DESIGN", Segment.OTHER],
  ["LAVANDERIA ORIENTAL WASH", Segment.HOME],
  ["Claudiana Correntino | Psicóloga", Segment.HEALTH],
  ["Isabela Costa | Psicoterapeuta", Segment.HEALTH],
  ["RR Laboratório de Próteses Dentária", Segment.HEALTH],
  ["BISPO ADVOCACIA", Segment.OTHER],
  ["Flavia Cafilista Nails", Segment.BEAUTY],
  ["LAINARA SANTOS SAÚDE E ESTÉTICA", Segment.HEALTH],
  ["Carol Alvim Psicóloga", Segment.HEALTH],
  ["ANDREZA GONÇALVES PSICOLOGA", Segment.HEALTH],
  ["Isabella Sales Nutricionista", Segment.HEALTH],
  ["INSPIRE A MENTE", Segment.HEALTH],
  ["Hpes Podologia", Segment.BEAUTY],
  ["DR. VICTOR VITORINO", Segment.HEALTH],
  ["Clínica odontológica Unident", Segment.HEALTH],
  ["PSICÓLOGO CASTINALDO ROCHA", Segment.HEALTH],
  ["Instituto de Olhos Santa Genoveva", Segment.HEALTH],
  ["Dra. Gabriela Grolli", Segment.HEALTH],
  ["VOUPRACALDAS", Segment.LEISURE],
  ["Consultório de Fonoaudiologia", Segment.HEALTH],
  ["Gabriela Andreane | Psicologia", Segment.HEALTH],
  ["Ibsen Acupuntura", Segment.HEALTH],
  ["Anne Francis | Psicóloga", Segment.HEALTH],
  ["PEQUENOS PEDIATRIA", Segment.HEALTH],
  ["Estética e Saúde Jady Freitas", Segment.BEAUTY],
  ["Mariângela Ceccon", Segment.BEAUTY],
  ["Keila Santos Fisioterapeuta", Segment.HEALTH],
  ["Studio de pilates Sara", Segment.HEALTH],
  ["Psicóloga Gabriella Chiovato", Segment.HEALTH],
  ["William Lopes Pediatra", Segment.HEALTH],
  ["Jhully Oliveira - Psicóloga", Segment.HEALTH],
  ["Patrícia Naves Nutricionista", Segment.HEALTH],
  ["PRADO E NEVES ODONTOLOGIA", Segment.HEALTH],
  ["AF/Nails Designer", Segment.BEAUTY],
  ["Neuropsicopedagoga - Alice Rosa Silva", Segment.HEALTH],
  ["Espaço Beleza e Arte Sandra", Segment.BEAUTY],
  ["BRUNA ALMEIDA ESTETICA", Segment.BEAUTY],
  ["GABRIELA CARVALHO PAIVA", Segment.PET],
  ["Ana Cláudia Psicóloga", Segment.HEALTH],
  ["CONSULTEJATELEMDICINA24H", Segment.HEALTH],
  ["Letícia Cota | Psicóloga", Segment.HEALTH],
  ["Psicóloga Clínica Ana Mendes", Segment.HEALTH],
  ["RAITS RESTAURANTE", Segment.FOOD],
  ["Daniele Guimarães Psicologia", Segment.HEALTH],
  ["FOCALIZA RASTREADOR", Segment.AUTO],
  ["EZEN ACESSORIA DE MARKETING", Segment.OTHER],
  ["TEACHER CAMILA NASCIMENTO", Segment.EDUCATION],
  ["Victoria Oliveira | Nutricionista", Segment.HEALTH],
  ["Tatiana Rios | Psicóloga", Segment.HEALTH],
  ["LUKIANI FIBRA", Segment.BEAUTY],
  ["RAQUEL UNHAS", Segment.BEAUTY],
  ["EQUILIBRIUM BELEZA E SAÚDE", Segment.BEAUTY],
  ["DILSINHO RECUPERADORA", Segment.AUTO],
  ["TOP DANCE STUDIO DE DANÇA", Segment.FITNESS],
  ["Taynara Prestes - Psicologia", Segment.HEALTH],
  ["MARCELO FIGUEIREDO", Segment.HOME],
  ["BÁRBARA BIASOLI NUTRIÇÃO", Segment.HEALTH],
  ["NATHALIA MARQUES - ARQUITETURA", Segment.HOME],
  ["Raio Serviços Elétricos", Segment.HOME],
  ["SEVEN", Segment.BEAUTY],
  ["Dra Emily Bastos", Segment.BEAUTY],
  ["Psicóloga Andryelle Borges", Segment.HEALTH],
  ["CENTRO DA VISAO", Segment.HEALTH],
  ["BIANCA FLORES", Segment.HOME],
  ["GRANDES LAGOS TUMULOS", Segment.HOME],
  ["PSICRER CENTRO DE TREINAMENTOS", Segment.HEALTH],
  ["Lorraynearaujobeauty", Segment.BEAUTY],
  ["Psicologa Viviane Santos", Segment.HEALTH],
  ["D&C SERVIÇOS", Segment.OTHER],
  ["Espaço viver bem", Segment.HEALTH],
  ["AB NEUROPSICOLOGIA", Segment.HEALTH],
  ["IPOG UBERLANDIA", Segment.EDUCATION],
  ["RAFAELLA LACKMANN UNHAS", Segment.BEAUTY],
  ["Ionice Ribeiro - Psicóloga", Segment.HEALTH],
  ["SOLANGE RODOVALHO HAIR NAILS", Segment.BEAUTY],
  ["ESTATIZE AGÊNCIA ONLINE", Segment.OTHER],
  ["Easy zen terapias", Segment.HEALTH],
  ["Axs Online", Segment.HOME],
  ["AMORE LINGERIE", Segment.BEAUTY],
  ["studio elaine beauty", Segment.BEAUTY],
  ["DRA AQUILA VALENTE", Segment.HEALTH],
  ["Laura Solé", Segment.HEALTH],
  ["Eurolima-espaço de saúde", Segment.HEALTH],
  ["CENTRO VETERINÁRIO DE IMAGEM", Segment.PET],
  ["Harmonize", Segment.HEALTH],
  ["PRONTO SOCORRO VETERINÁRIO", Segment.PET],
  ["ART AGENCIA", Segment.OTHER],
  ["GAUCHAO AÇAI", Segment.FOOD],
  ["FERRAGISTA E PESCA LOPES", Segment.PET],
  ["IMPÉRIO EDGE PAINEL SOLAR", Segment.HOME],
  ["DR MARCOS GONÇALVES", Segment.HEALTH],
  ["HOSPITAL DOS OCULOS LUIZOTE", Segment.HEALTH],
  ["Psicóloga Skarlet Silva", Segment.HEALTH],
  ["PSICOTERAPEUTA MARIA LAURA PACHECO", Segment.HEALTH],
  ["Hélio Junior Psicólogo", Segment.HEALTH],
  ["CRIS LOPES", Segment.EDUCATION],
  ["ROSE MEL ATELIE", Segment.FOOD],
  ["M.A. BRINDES E PRESENTES", Segment.OTHER],
  ["Guilherme Bessa", Segment.HEALTH],
  ["Clínica Psicológica Jéssica", Segment.HEALTH],
  ["DRA ANA CRISTINA", Segment.HEALTH],
  ["CLÍNICA ODONTO KEY BOR", Segment.HEALTH],
  ["DR ARNALDO MACHADO BORGES", Segment.HEALTH],
  ["BAROGASTRO", Segment.HEALTH],
  ["CARBOSS", Segment.AUTO],
  ["DR JORGE DE PAULO MENDES", Segment.HEALTH],
  ["Óptica Lilian", Segment.HEALTH],
  ["Instituto Buscadores", Segment.HEALTH],
  ["LORENA VILELA DOULA", Segment.BEAUTY],
  ["VIVADENT", Segment.HEALTH],
  ["Rapariga Hard", Segment.BEAUTY],
  ["Luiza Reis", Segment.HEALTH],
  ["DOCCTOR MED GRANADA", Segment.HEALTH],
  ["COLLOR MAKE STORE", Segment.BEAUTY],
  ["ORALVITTA ODONTOLOGIA", Segment.HEALTH],
  ["Franco & Costa Advogados", Segment.OTHER],
  ["MGM ESTÉTICA", Segment.HOME],
  ["odonto continental", Segment.HEALTH],
  ["Dra Thalita Galvão", Segment.HEALTH],
  ["Marjan Joias e Semijoias", Segment.BEAUTY],
  ["WNS Fit", Segment.FITNESS],
  ["Espaço Mari Valentino", Segment.BEAUTY],
  ["DI SOTTI", Segment.BEAUTY],
  ["ROSELIBISCUIT", Segment.OTHER],
  ["CLÍNICA IMPERIUM", Segment.HEALTH],
  ["GONÇALVES ADVOCACIA", Segment.OTHER],
  ["DR BERNARDO ROSA", Segment.HEALTH],
  ["VIEIRA S WRAP", Segment.AUTO],
  ["INGRID FARIA NUTRICIONISTA", Segment.HEALTH],
  ["POLO EDUCACIONAL UBERLANDIA", Segment.EDUCATION],
  ["ECBEU IDIOMAS E CULTURA", Segment.EDUCATION],
  ["MF TRAINING", Segment.HEALTH],
  ["Bianca Figueiredo Nails", Segment.BEAUTY],
  ["Concertec", Segment.HOME],
  ["NM Fisioterapia", Segment.HEALTH],
  ["Nutricionista Amanda Vitorino", Segment.HEALTH],
  ["ROSA GALERIA DIGITAL", Segment.BEAUTY],
  ["Juliano Máximo", Segment.OTHER],
  ["CONNFISIO", Segment.HEALTH],
  ["SHD Home Care", Segment.HEALTH],
  ["FARMA JORGE", Segment.HEALTH],
  ["DR. EXAME", Segment.HEALTH],
  ["MECÂNICA PRECISÃO", Segment.AUTO],
  ["DR THIAGO MÉDICO GERIATRA", Segment.HEALTH],
  ["CHICK&ATREVIDA MODA INTIMA", Segment.BEAUTY],
  ["Ale Borges", Segment.BEAUTY],
  ["Ana Paula Fisioestética", Segment.HEALTH],
  ["Karine Helena", Segment.HEALTH],
  ["ALONGAMENTO E CIA", Segment.BEAUTY],
  ["MS EMPRESARIAL SALGADOS", Segment.FOOD],
  ["ANDRADE SOLUÇÕES", Segment.HOME],
  ["Murilo Rezende Nutricionista", Segment.HEALTH],
  ["ESCOLA PARK DE IDIOMAS", Segment.EDUCATION],
  ["ISABELLA BLANCATO", Segment.BEAUTY],
  ["Espaço Patrícia Sousa", Segment.BEAUTY],
  ["Studio Dog & Cat", Segment.PET],
  ["Instituto Rodrigo Miranda", Segment.BEAUTY],
  ["FOX INOVACOES", Segment.HOME],
  ["PAPILLON ODONTOLOGIA", Segment.HEALTH],
  ["Lia braids", Segment.BEAUTY],
  ["BIODIAGNOSTICO", Segment.HEALTH],
  ["Pet shop bioticao", Segment.PET],
  ["AUTO ESCOLA MARANATHA", Segment.EDUCATION],
  ["La Blanc Semijoias", Segment.BEAUTY],
  ["Leidi Rocha", Segment.BEAUTY],
  ["IAGO FERNANDES JUNQUEIRA", Segment.HEALTH],
  ["Bruna Faria - Fisioterapeuta", Segment.HEALTH],
  ["ESPAÇO LIFT", Segment.HEALTH],
  ["JM CONVENIENCIA", Segment.FOOD],
  ["FISIOVET", Segment.PET],
  ["RS&TN SERVIÇOS ESPECIALIZADOS", Segment.HEALTH],
  ["MIRE AS ESTRELAS", Segment.HEALTH],
  ["Neuropsi Janaína Diogo", Segment.HEALTH],
  ["Thiago Cecote Barber", Segment.BEAUTY],
  ["Prudente & Rezende Odontologia", Segment.HEALTH],
  ["Junior Style", Segment.BEAUTY],
  ["BRUNO MOTOS", Segment.AUTO],
  ["Talita Oliveira Nutricionista", Segment.HEALTH],
  ["TALITA ROCHA - PSICOLOGIA", Segment.HEALTH],
  ["Trancista Bela", Segment.BEAUTY],
  ["Clínica Lm Fisioterapia", Segment.HEALTH],
  ["Marcela Alves Sobral", Segment.BEAUTY],
  ["Bicho Felpudo", Segment.PET],
  ["Sowe Paper", Segment.OTHER],
  ["WVN VIDRAÇARIA", Segment.HOME],
  ["Espaço Nutrilótus", Segment.BEAUTY],
  ["TALYTA DE SOUZA GARCIA", Segment.HEALTH],
  ["Status Barbearia", Segment.BEAUTY],
  ["MK ODONTOLOGIA INTEGRADA", Segment.HEALTH],
  ["RENATA RIBEIRO CURSOS", Segment.HEALTH],
  ["PRISCILA KAREN ODONTO", Segment.HEALTH],
  ["DP MAX AUTO PEÇAS", Segment.AUTO],
  ["Unicar Autocenter", Segment.AUTO],
  ["MULTICLINICA CARDIOLOGIA", Segment.HEALTH],
  ["CIA DA BELEZA", Segment.BEAUTY],
  ["S.O.S REPAROS", Segment.HOME],
  ["INSTITUTO IMPLEMENTAR", Segment.HEALTH],
  ["Caroline Moura Pediatria", Segment.HEALTH],
  ["Dra. Leticia Araújo", Segment.HEALTH],
  ["REZENDE SERVICOS MEDICOS", Segment.HEALTH],
  ["ODONTOCLINIC", Segment.HEALTH],
  ["Styllus recuperadora", Segment.AUTO],
  ["Azul Autismo", Segment.HEALTH],
  ["Studio Pilates Jack Carvalho", Segment.FITNESS],
  ["Clínica Belle Harmonize", Segment.BEAUTY],
  ["Tathiana Senechal - Psicóloga", Segment.HEALTH],
  ["AMPLIUS - PRODUTOS AUDIOLOGICOS", Segment.HEALTH],
  ["PSICÓLOGO ADRIANO MARCOS", Segment.HEALTH],
  ["Sara Psicopedagoga", Segment.HEALTH],
  ["Vitta Pilates e Fisioterapia", Segment.HEALTH],
  ["Natalia Lash Designer", Segment.BEAUTY]
];

// GENERATE EXACTLY 1607 PARTNERS
const generateFullPartnerList = (): Partner[] => {
  const neighborhoods = ['Centro', 'Santa Mônica', 'Martins', 'Fundinho', 'Granja Marileusa', 'Tibery', 'Jardim Patrícia', 'Saraiva', 'Roosevelt', 'Luizote', 'Planalto', 'Tocantins'];
  
  // Total target is 1607
  return Array.from({ length: 1607 }).map((_, index) => {
    // If we have real data from the user list, use it. Otherwise loop or generate generic.
    const realEntry = rawPartnerDatabase[index] || rawPartnerDatabase[index % rawPartnerDatabase.length];
    const name = realEntry[0] as string;
    const segment = realEntry[1] as Segment;
    
    const usageScore = Math.floor(Math.random() * 100);
    const randomRevenue = Math.floor(Math.random() * 9000) + 100;
    
    let status = ContractStatus.ACTIVE;
    if (usageScore < 25) status = ContractStatus.RISK;
    else if (usageScore < 55) status = ContractStatus.REVIEW;

    return {
      id: `partner-${index}`,
      name: name,
      location: neighborhoods[index % neighborhoods.length],
      segment: segment,
      contractStart: '2023-01-15',
      usageScore: usageScore,
      monthlyRevenue: randomRevenue,
      benefits: ['Benefício Rede Valorize', 'Desconto Exclusivo'],
      status: status,
      isOnWebsite: usageScore > 25, 
      isTop20: usageScore > 80
    };
  });
};

type Tab = 'dashboard' | 'partners' | 'map';

const App: React.FC = () => {
  const [partners, setPartners] = useState<Partner[]>([]);
  const [loading, setLoading] = useState(true);
  const [activeTab, setActiveTab] = useState<Tab>('dashboard');
  const [saveStatus, setSaveStatus] = useState<'idle' | 'saving' | 'saved'>('idle');

  useEffect(() => {
    const savedPartners = localStorage.getItem('valorize_partners_v2');
    if (savedPartners) {
      setPartners(JSON.parse(savedPartners));
    } else {
      setPartners(generateFullPartnerList());
    }
    setLoading(false);
  }, []);

  const handleManualSave = () => {
    setSaveStatus('saving');
    localStorage.setItem('valorize_partners_v2', JSON.stringify(partners));
    setTimeout(() => {
      setSaveStatus('saved');
      setTimeout(() => setSaveStatus('idle'), 2000);
    }, 800);
  };

  const handleAddPartner = (newPartner: Partner) => {
    setPartners(prev => [newPartner, ...prev]);
  };

  const handleUpdatePartner = (updatedPartner: Partner) => {
    setPartners(prev => prev.map(p => p.id === updatedPartner.id ? updatedPartner : p));
  };

  const handleDeletePartner = (id: string) => {
    setPartners(prev => prev.filter(p => p.id !== id));
  };

  const stats = useMemo(() => {
    const totalPartners = partners.length;
    const activeOnSite = partners.filter(p => p.isOnWebsite).length;
    const reviewContracts = partners.filter(p => p.status !== ContractStatus.ACTIVE).length;
    const activePercent = totalPartners > 0 ? (activeOnSite / totalPartners) * 100 : 0;
    return { totalPartners, activeOnSite, reviewContracts, activePercent };
  }, [partners]);

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-50">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-orange-500"></div>
      </div>
    );
  }

  const NavItem = ({ id, label, icon: Icon }: { id: Tab, label: string, icon: any }) => (
    <button 
      onClick={() => setActiveTab(id)}
      className={`w-full flex items-center gap-3 px-4 py-3 rounded-lg font-medium transition-colors ${
        activeTab === id 
          ? 'bg-orange-50 text-orange-700' 
          : 'text-gray-600 hover:bg-gray-50 hover:text-gray-900'
      }`}
    >
      <Icon size={20} />
      {label}
    </button>
  );

  const renderDashboard = () => {
    const segmentCounts = Object.values(Segment).map(seg => {
      const count = partners.filter(p => p.segment === seg).length;
      return { segment: seg, count };
    }).sort((a, b) => b.count - a.count);

    return (
      <>
        <div className="grid grid-cols-1 md:grid-cols-3 lg:grid-cols-3 gap-6 mb-8">
          <StatsCard title="Total de Parceiros" value={stats.totalPartners} description="Rede Valorize" icon={Users} color="blue"/>
          <StatsCard title="Vigentes no Site" value={stats.activeOnSite} description="Visíveis ao Público" icon={Globe} color="green"/>
          <StatsCard title="Status Crítico" value={stats.reviewContracts} description="Ação Necessária" icon={AlertTriangle} color="orange"/>
        </div>
        
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 mb-8">
          <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-100 flex flex-col h-[450px]">
              <div className="mb-6 shrink-0">
                  <h3 className="text-lg font-bold text-gray-800">Segmentação da Rede</h3>
                  <p className="text-sm text-gray-500">Distribuição total dos {stats.totalPartners} parceiros.</p>
              </div>
              <div className="flex-1 overflow-y-auto custom-scrollbar pr-2 space-y-5">
                  {segmentCounts.map(item => {
                      const pct = partners.length > 0 ? Math.round((item.count / partners.length) * 100) : 0;
                      return (
                          <div key={item.segment}>
                              <div className="flex justify-between text-sm mb-2">
                                  <span className="text-gray-700 font-medium">{item.segment}</span>
                                  <span className="text-gray-500">{item.count} ({pct}%)</span>
                              </div>
                              <div className="w-full bg-gray-100 rounded-full h-2.5">
                                  <div 
                                    className="bg-orange-500 h-2.5 rounded-full transition-all duration-500" 
                                    style={{ width: `${pct}%` }}
                                  ></div>
                              </div>
                          </div>
                      )
                  })}
              </div>
          </div>
          <ActivePartnersChart data={partners} />
        </div>

        {/* RESUMO DOS RESULTADOS */}
        <div className="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden mb-8">
            <div className="p-6 bg-gradient-to-r from-[#1e3a8a] to-[#1e40af] text-white">
                <div className="flex flex-col md:flex-row md:items-center justify-between gap-6">
                    <div className="flex-1">
                        <div className="flex items-center gap-2 mb-2">
                            <Activity size={20} className="text-orange-400" />
                            <h3 className="text-lg font-bold">Resumo Estratégico da Rede</h3>
                        </div>
                        <p className="text-blue-100 text-sm leading-relaxed max-w-2xl">
                            Atualmente, a Rede Valorize conta com uma base consolidada de <strong>{stats.totalPartners}</strong> parceiros em Uberlândia. 
                            Deste total, <strong>{stats.activeOnSite}</strong> parceiros estão com status de ativação concluído e visíveis para os nossos beneficiários.
                        </p>
                    </div>
                    <div className="flex items-center gap-4 bg-white/10 p-4 rounded-2xl backdrop-blur-md border border-white/20">
                        <div className="text-right">
                            <p className="text-xs font-medium text-blue-200 uppercase tracking-wider">Taxa de Ativação</p>
                            <div className="flex items-baseline gap-1">
                                <span className="text-4xl font-black text-white">{stats.activePercent.toFixed(1)}%</span>
                                <ArrowUpRight size={20} className="text-emerald-400" />
                            </div>
                        </div>
                        <div className="w-16 h-16 rounded-full border-4 border-emerald-500/30 flex items-center justify-center relative">
                            <div 
                              className="absolute inset-0 rounded-full border-4 border-emerald-500 transition-all duration-1000"
                              style={{ 
                                clipPath: `polygon(50% 50%, -50% -50%, ${stats.activePercent > 50 ? '150% -50%' : '50% -50%'}, ${stats.activePercent > 75 ? '150% 150%' : stats.activePercent > 50 ? '150% 150%' : '50% 50%'})`
                              }}
                            />
                            <CheckCircle2 size={24} className="text-emerald-400" />
                        </div>
                    </div>
                </div>
            </div>
            <div className="p-4 bg-gray-50 flex flex-wrap gap-4 items-center justify-center md:justify-start border-t border-gray-100">
                <div className="flex items-center gap-2 text-xs font-semibold text-gray-500 bg-white px-3 py-1.5 rounded-full border border-gray-200">
                    <div className="w-2 h-2 rounded-full bg-emerald-500" />
                    {stats.activeOnSite} Ativos e Vigentes
                </div>
                <div className="flex items-center gap-2 text-xs font-semibold text-gray-500 bg-white px-3 py-1.5 rounded-full border border-gray-200">
                    <div className="w-2 h-2 rounded-full bg-orange-500" />
                    {stats.totalPartners - stats.activeOnSite} Pendentes/Ocultos
                </div>
                <div className="text-xs text-gray-400 ml-auto italic">
                    Última atualização: {new Date().toLocaleDateString('pt-BR')}
                </div>
            </div>
        </div>
      </>
    );
  };

  return (
    <div className="flex min-h-screen bg-[#F3F4F6]">
      <aside className="w-64 bg-white border-r border-gray-200 hidden md:flex flex-col fixed h-full z-10">
        <div className="p-6 border-b border-gray-100">
          <div className="flex items-center gap-2">
            <span className="text-xl font-bold text-gray-800">Valorize<span className="text-orange-600">+</span></span>
          </div>
          <p className="text-xs text-gray-400 mt-1 uppercase tracking-wider font-medium">Gestão de Saúde</p>
        </div>
        <nav className="flex-1 p-4 space-y-1">
          <NavItem id="dashboard" label="Dashboard" icon={LayoutDashboard} />
          <NavItem id="map" label="Mapa da Rede" icon={MapIcon} />
          <NavItem id="partners" label="Parceiros" icon={Users} />
        </nav>
      </aside>

      <main className="flex-1 md:ml-64 p-4 md:p-8">
        <header className="flex flex-col md:flex-row md:justify-between md:items-center gap-4 mb-8">
          <div>
            <h1 className="text-2xl font-bold text-gray-900">
              {activeTab === 'dashboard' ? 'Visão Geral' : activeTab === 'partners' ? 'Parceiros' : 'Geolocalização'}
            </h1>
            <p className="text-gray-500">Monitoramento da rede de benefícios Valorize + Saúde.</p>
          </div>
          <div className="flex items-center gap-4">
            <button 
              onClick={handleManualSave}
              disabled={saveStatus === 'saving'}
              className={`flex items-center gap-3 px-6 py-2.5 rounded-xl text-white font-semibold shadow-lg transition-all active:scale-95 ${
                saveStatus === 'saved' ? 'bg-emerald-600' : 'bg-[#1e3a8a] hover:bg-[#1e40af]'
              }`}
            >
              {saveStatus === 'saved' ? (
                <><Check size={18} /> Alterações Salvas!</>
              ) : (
                <><Save size={18} /> Salvar Alterações</>
              )}
            </button>
            
            <button className="relative p-2 bg-white rounded-lg border border-gray-200 text-gray-500 hover:text-gray-700">
              <Bell size={20} />
              <span className="absolute top-1.5 right-1.5 w-2 h-2 bg-red-500 rounded-full"></span>
            </button>
          </div>
        </header>

        {activeTab === 'dashboard' && renderDashboard()}
        {activeTab === 'partners' && (
          <div className="space-y-6">
            <PartnerManager partners={partners} onAdd={handleAddPartner} onUpdate={handleUpdatePartner} onDelete={handleDeletePartner} />
          </div>
        )}
        {activeTab === 'map' && <MapDistribution partners={partners} />}
      </main>
    </div>
  );
};

export default App;
